### PR TITLE
Miac41 cc 18

### PR DESCRIPTION
**Pull request by Ayo478**
Completed functionality of ticket 18

### CODE REVIEW

**Comment by Miguel787** [comment]
lets discuss tomorrow the files changes warehousepage.jsx should have something in there it looks like yours doesn't have the info it needs I want to hold off on approving this one till we look at it

**Comment by itsnickrus** [comment]
Reviewed with ayo and TA and looks good!

**Review by itsnickrus — APPROVED** [review]
Looks good!

**Review by xfroggy — APPROVED** [review]
Looks good, I see you've added in a proxy.  Not sure how this will affect our existing api links, if there are any issues we can just remove the 'http://localhose:8080' part of our links.  Just something to keep in mind, other than that, all good!

**Pull request merged**
